version: '3.8'
services:
  grok2api:
    build: .
    container_name: grok_api
    ports:
      - "4000:3000"
    environment:
      - TUMY_KEY=
      - IS_CUSTOM_SSO=false
      - ISSHOW_SEARCH_RESULTS=false
      - PORT=3000
      - SHOW_THINKING=true
      - SSO=
    restart: unless-stopped
